name: Build
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: secondlife/action-autobuild@v3
      - uses: secondlife/action-autobuild-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
